/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bhk' at '11/27/16 9:46 AM' with Gradle 3.0
 *
 * @author bhk, @date 11/27/16 9:46 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
